name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # Trigger on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Workflow will run on Ubuntu virtual machines

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout code from the repository

      - name: Use Node.js 20  # Use a specific Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install  # Install dependencies
        working-directory: client

      - name: Build project
        run: npm run build  # Build the app for production
        working-directory: client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build